import '../dist/forecast-schema.js';
// Public weather storage. The owner approved this exact workflow/main trust and dedicated R2 binding.
export const FORECAST_WRITER_ENABLED = true;
export const FORECAST_POLICY = Object.freeze({issuer:'https://token.actions.githubusercontent.com',jwks:'https://token.actions.githubusercontent.com/.well-known/jwks',audience:'https://enso-weather-atlas.bensonlee5.chatgpt.site',repository:'bensonlee5/enso-atlas',repositoryID:'1396914466',ownerID:'4791094',ref:'refs/heads/main',workflow:'bensonlee5/enso-atlas/.github/workflows/refresh-weather.yml@refs/heads/main'});
export const FORECAST_FILES = Object.freeze(['cfs-weekly-raw-60days.json','cfs-weekly-anomalies.json','enso-observations.json','ensemble-percentiles.json','verification.json','cfs-global-60days.json','aifs-global-snapshots.json']);
const FC_AUDIT='ensemble-member-means.json.gz',FC_LATEST='forecasts/latest.json',FC_HASH=/^[a-f0-9]{64}$/;
function forecastLimit(name){if(name===FC_AUDIT)return 8000000;if(FORECAST_FILES.includes(name))return 5000000;if(name==='archive/index.json')return 200000;if(/^archive\/[0-9]{8}00\.json$/.test(name))return 200000;return 0}
function forecastFail(message,status=400){const e=new Error(message);e.status=status;throw e}
function forecastAssert(ok,message,status=400){if(!ok)forecastFail(message,status)}
function forecastCanonical(value){if(Array.isArray(value))return '['+value.map(forecastCanonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+forecastCanonical(value[k])).join(',')+'}';return JSON.stringify(value)}
async function forecastHash(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function forecastBody(request,limit,upstream=false){const supplied=request.headers.get('content-length');if(supplied!==null)forecastAssert(/^\d+$/.test(supplied)&&Number(supplied)<=limit,'Payload too large',413);forecastAssert(upstream||!request.headers.get('content-encoding'),'Encoded request body unsupported',415);forecastAssert(request.body,'Missing body');const reader=request.body.getReader(),chunks=[];let count=0;try{for(;;){const {done,value}=await reader.read();if(done)break;count+=value.length;if(count>limit)forecastFail('Payload too large',413);chunks.push(value)}}catch(e){await reader.cancel();throw e}const result=new Uint8Array(count);let offset=0;for(const b of chunks){result.set(b,offset);offset+=b.length}return result}
function forecastJSON(bytes){try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}catch{forecastFail('Invalid JSON')}}
function forecastB64(value){forecastAssert(typeof value==='string'&&/^[A-Za-z0-9_-]+$/.test(value),'Invalid token',401);try{return Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))}catch{forecastFail('Invalid token',401)}}
function forecastClaims(c,p,now){
 const sec=Math.floor(now/1000),legacy='repo:'+p.repository+':ref:'+p.ref,immutable='repo:bensonlee5@'+p.ownerID+'/enso-atlas@'+p.repositoryID+':ref:'+p.ref;
 forecastAssert(c.iss===p.issuer&&c.aud===p.audience&&[legacy,immutable].includes(c.sub),'Untrusted token scope',403);
 forecastAssert(c.repository===p.repository&&c.repository_id===p.repositoryID&&c.repository_owner_id===p.ownerID&&c.repository_owner==='bensonlee5'&&c.repository_visibility==='public'&&c.runner_environment==='github-hosted','Untrusted repository',403);
 forecastAssert(c.ref===p.ref&&c.ref_type==='branch'&&c.workflow_ref===p.workflow&&['schedule','workflow_dispatch','push'].includes(c.event_name),'Untrusted workflow',403);
 forecastAssert(!c.head_ref&&!c.base_ref&&!c.environment&&!c.job_workflow_ref&&!c.job_workflow_sha,'Unexpected caller context',403);
 forecastAssert(/^[1-9][0-9]{0,19}$/.test(c.run_id||'')&&/^[1-9][0-9]{0,5}$/.test(c.run_attempt||'')&&/^[a-f0-9]{40}$/.test(c.sha||'')&&/^[a-f0-9]{40}$/.test(c.workflow_sha||''),'Invalid run identity',403);
 forecastAssert(['iat','nbf','exp'].every(k=>Number.isSafeInteger(c[k]))&&c.iat<=sec+30&&c.nbf<=sec+30&&c.exp>sec&&c.iat>=sec-600&&c.exp-c.iat<=600&&c.exp>c.iat&&c.nbf>=c.iat-600&&c.nbf<=c.iat+30,'Expired or invalid token time',401);
 return c;
}
function forecastDate(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(value)&&Number.isFinite(Date.parse(value))}
async function forecastEnvelope(m){
 forecastAssert(m&&m.schemaVersion===1&&m.storageVersion===1&&forecastDate(m.generatedAt)&&Date.parse(m.generatedAt)<=Date.now()+300000,'Invalid manifest version/time');
 forecastAssert(m.files&&m.objects&&m.initializations&&FC_HASH.test(m.releaseID),'Invalid manifest envelope');
 forecastAssert(Object.keys(m.files).sort().join('|')===FORECAST_FILES.slice().sort().join('|'),'Incomplete browser bundle');
 const names=Object.keys(m.objects);forecastAssert(names.length>=9&&names.length<=410&&names.includes(FC_AUDIT)&&names.includes('archive/index.json'),'Invalid storage object set');
 let total=0;for(const name of names){const d=m.objects[name],limit=forecastLimit(name);forecastAssert(limit&&d&&FC_HASH.test(d.sha256)&&Number.isSafeInteger(d.bytes)&&d.bytes>0&&d.bytes<=limit,'Invalid object metadata');total+=d.bytes}
 forecastAssert(total<=64000000,'Release exceeds bounded total size');
 for(const name of FORECAST_FILES)forecastAssert(forecastCanonical(m.files[name])===forecastCanonical(m.objects[name]),'Browser/object metadata mismatch');
 for(const key of ['raw','anomaly','ensemble','ensoObservation','globalCfs','aifs'])forecastAssert(forecastDate(m.initializations[key])&&Date.parse(m.initializations[key])<=Date.now()+300000,'Invalid source initialization');
 const core={files:m.files,objects:m.objects,initializations:m.initializations};forecastAssert(await forecastHash(new TextEncoder().encode(forecastCanonical(core)))===m.releaseID,'Release identity mismatch');return m;
}
function forecastObjectKey(hash,name){return 'forecasts/objects/'+hash+'/'+name}
function forecastResponse(body,status=200,headers={}){return new Response(body,{status,headers:{'x-content-type-options':'nosniff','cache-control':'no-store',...headers}})}

export function createForecastService({fetcher=globalThis.fetch,clock=()=>Date.now(),enabled=FORECAST_WRITER_ENABLED,policy=FORECAST_POLICY}={}){
 let jwks=null,jwksUntil=0,jwksPending=null,lastJWKSAttempt=0;
 async function keys(){const now=clock();if(jwks&&now<jwksUntil)return jwks;if(jwksPending)return jwksPending;forecastAssert(now-lastJWKSAttempt>10000,'Identity provider unavailable',503);lastJWKSAttempt=now;jwksPending=(async()=>{const response=await fetcher(policy.jwks,{redirect:'error',signal:AbortSignal.timeout(8000)});forecastAssert(response.ok,'Identity provider unavailable',503);const bytes=await forecastBody(response,100000,true),data=forecastJSON(bytes);forecastAssert(Array.isArray(data.keys)&&data.keys.length>0&&data.keys.length<=20,'Identity provider unavailable',503);jwks=data.keys.filter(k=>k.kty==='RSA'&&k.alg==='RS256'&&k.use==='sig'&&typeof k.kid==='string');jwksUntil=clock()+300000;return jwks})().finally(()=>{jwksPending=null});return jwksPending}
 async function authorize(request){forecastAssert(enabled,'Forecast writer is disabled',503);const authorization=request.headers.get('authorization')||'';forecastAssert(authorization.startsWith('Bearer ')&&authorization.length<24000,'Authentication required',401);const token=authorization.slice(7),parts=token.split('.');forecastAssert(parts.length===3,'Invalid token',401);const header=forecastJSON(forecastB64(parts[0])),claims=forecastJSON(forecastB64(parts[1]));forecastAssert(header.alg==='RS256'&&header.typ==='JWT'&&typeof header.kid==='string'&&header.kid.length<200&&!header.jku&&!header.x5u&&!header.crit,'Untrusted token header',401);forecastClaims(claims,policy,clock());const key=(await keys()).find(k=>k.kid===header.kid);forecastAssert(key,'Unknown signing key',401);const imported=await crypto.subtle.importKey('jwk',key,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);forecastAssert(await crypto.subtle.verify('RSASSA-PKCS1-v1_5',imported,forecastB64(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1])),'Invalid token signature',401);return claims}
 async function latest(bucket){const item=await bucket.get(FC_LATEST);if(!item)return null;const bytes=await item.arrayBuffer();forecastAssert(bytes.byteLength<200000,'Stored manifest too large',503);return {item,data:await forecastEnvelope(forecastJSON(bytes))}}
 async function readObject(bucket,hash,name,head=false){const key=forecastObjectKey(hash,name),item=head?await bucket.head(key):await bucket.get(key);if(!item)return forecastResponse('Forecast object unavailable',404);forecastAssert(item.customMetadata?.sha256===hash&&item.customMetadata?.filename===name&&item.size<=forecastLimit(name),'Stored object invalid',503);return forecastResponse(head?null:item.body,200,{'content-type':name.endsWith('.gz')?'application/gzip':'application/json; charset=utf-8','content-length':String(item.size),etag:'"'+hash+'"','cache-control':'public,max-age=31536000,immutable'})}
 async function validateProduct(bucket,name,meta,m){const item=await bucket.get(forecastObjectKey(meta.sha256,name));forecastAssert(item&&item.size===meta.bytes,'Missing or incomplete product');const bytes=await item.arrayBuffer();forecastAssert(bytes.byteLength===meta.bytes&&await forecastHash(bytes)===meta.sha256,'Stored product integrity mismatch');const p=forecastJSON(bytes),runKey={'cfs-weekly-raw-60days.json':'raw','cfs-weekly-anomalies.json':'anomaly','ensemble-percentiles.json':'ensemble','cfs-global-60days.json':'globalCfs','aifs-global-snapshots.json':'aifs'}[name];if(runKey)forecastAssert((name==='cfs-weekly-anomalies.json'?p.initialDate:p.run)===m.initializations[runKey],'Product/manifest initialization mismatch');if(name==='enso-observations.json')forecastAssert(p.observations?.at(-1)?.date===m.initializations.ensoObservation,'Observation/manifest date mismatch');if(name==='ensemble-percentiles.json'){const a=p.memberMeansArtifact;forecastAssert(p.schemaVersion===3&&p.coverage==='global'&&p.memberCount===16&&p.gridCoordinates?.length>=4000&&p.gridCoordinates.length<6000&&p.weeks?.length===8&&p.remainingDays57to60&&a?.sha256===m.objects[FC_AUDIT].sha256&&a.bytes===m.objects[FC_AUDIT].bytes,'Incomplete worldwide ensemble/audit pairing')}return p}
 return {async handle(request,env={}){
  try{
   const url=new URL(request.url),path=url.pathname,method=request.method,bucket=env.FORECASTS;
   forecastAssert(bucket,'Forecast storage unavailable',503);forecastAssert([...url.searchParams.keys()].every(k=>k==='v')&&url.searchParams.getAll('v').length<=1,'Unexpected query');
   if(path==='/api/forecasts/manifest'&&['GET','HEAD'].includes(method)){const current=await latest(bucket);if(!current)return forecastResponse(JSON.stringify({error:'No validated forecast bundle has been published yet'}),404,{'content-type':'application/json'});return forecastResponse(method==='HEAD'?null:JSON.stringify(current.data),200,{etag:current.item.httpEtag||'"'+current.item.etag+'"','content-type':'application/json; charset=utf-8','cache-control':'no-store'})}
   const object=path.match(/^\/api\/forecasts\/objects\/([a-f0-9]{64})\/(.+)$/);
   if(object){const [,hash,name]=object;forecastAssert(forecastLimit(name),'Unsupported filename',404);if(['GET','HEAD'].includes(method))return await readObject(bucket,hash,name,method==='HEAD');forecastAssert(method==='PUT','Method not allowed',405);const claims=await authorize(request);const bytes=await forecastBody(request,forecastLimit(name));forecastAssert(bytes.length>0&&await forecastHash(bytes)===hash,'Upload integrity mismatch');if(!name.endsWith('.gz'))forecastJSON(bytes);else forecastAssert(bytes.length>20&&bytes[0]===31&&bytes[1]===139&&bytes[2]===8,'Invalid gzip audit artifact');const key=forecastObjectKey(hash,name),exists=await bucket.head(key);if(exists){forecastAssert(exists.size===bytes.length&&exists.customMetadata?.sha256===hash&&exists.customMetadata?.filename===name,'Conflicting immutable object',409);return forecastResponse(null,204)}const stored=await bucket.put(key,bytes,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:name.endsWith('.gz')?'application/gzip':'application/json'},customMetadata:{sha256:hash,filename:name,runID:claims.run_id}});if(!stored){const winner=await bucket.head(key);forecastAssert(winner&&winner.size===bytes.length&&winner.customMetadata?.sha256===hash,'Conflicting object upload',409)}return forecastResponse(null,201)}
   const release=path.match(/^\/api\/forecasts\/releases\/([a-f0-9]{64})\/manifest\.json$/);
   if(release&&['GET','HEAD'].includes(method)){const item=await bucket.get('forecasts/releases/'+release[1]+'.json');if(!item)return forecastResponse('Release not found',404);return forecastResponse(method==='HEAD'?null:item.body,200,{'content-type':'application/json; charset=utf-8','cache-control':'public,max-age=31536000,immutable'})}
   if(path==='/api/forecasts/promote'){
    forecastAssert(method==='POST','Method not allowed',405);const writer=await authorize(request);const m=await forecastEnvelope(forecastJSON(await forecastBody(request,200000))),current=await latest(bucket),match=request.headers.get('if-match'),none=request.headers.get('if-none-match');
    if(current)forecastAssert(match===(current.item.httpEtag||'"'+current.item.etag+'"')&&!none,'Manifest changed; restore and retry',412);else forecastAssert(!match&&none==='*','Initial publish requires If-None-Match: *',412);
    if(current){const prior=current.data.publication;if(prior){const run=BigInt(writer.run_id),old=BigInt(prior.runID),attempt=Number(writer.run_attempt);forecastAssert(run>old||(run===old&&attempt>=prior.attempt),'Older publisher run',409);forecastAssert(run!==old||attempt!==prior.attempt||m.releaseID===current.data.releaseID,'A run attempt cannot publish different releases',409)}for(const key of ['raw','anomaly','ensemble','ensoObservation','globalCfs','aifs'])forecastAssert(Date.parse(m.initializations[key])>=Date.parse(current.data.initializations[key]),'Forecast cycle regression',409);if(m.releaseID===current.data.releaseID)return forecastResponse(JSON.stringify({releaseID:m.releaseID,unchanged:true}),200,{'content-type':'application/json',etag:current.item.httpEtag})}
    const changed=Object.keys(m.objects).filter(name=>!current||forecastCanonical(current.data.objects[name])!==forecastCanonical(m.objects[name]));forecastAssert(changed.length<=18,'Too many changed objects in one publication');
    for(const name of changed){const meta=m.objects[name],head=await bucket.head(forecastObjectKey(meta.sha256,name));forecastAssert(head&&head.size===meta.bytes&&head.customMetadata?.sha256===meta.sha256&&head.customMetadata?.filename===name,'Missing validated object');if(/^archive\/[0-9]{8}00\.json$/.test(name)&&current?.data.objects[name])forecastAssert(current.data.objects[name].sha256===meta.sha256,'Issued archive cannot be rewritten',409)}
    const products={};for(const name of FORECAST_FILES)products[name]=await validateProduct(bucket,name,m.files[name],m);
    try{globalThis.AtlasForecastSchema.validatePublicProducts(products)}catch{forecastFail('Forecast product schema validation failed')}
    const audit=products['ensemble-percentiles.json'].memberMeansArtifact;forecastAssert(audit.sha256===m.objects[FC_AUDIT].sha256&&audit.bytes===m.objects[FC_AUDIT].bytes,'Ensemble/audit pairing mismatch');
    const indexMeta=m.objects['archive/index.json'],indexItem=await bucket.get(forecastObjectKey(indexMeta.sha256,'archive/index.json'));forecastAssert(indexItem,'Archive index missing');const archiveIndex=forecastJSON(await indexItem.arrayBuffer());forecastAssert(archiveIndex.schemaVersion===1&&Array.isArray(archiveIndex.issuances)&&archiveIndex.issuances.length<=400,'Invalid archive index');const archiveNames=new Set();for(const row of archiveIndex.issuances){const name='archive/'+row.path;forecastAssert(/^archive\/[0-9]{8}00\.json$/.test(name)&&forecastDate(row.run)&&forecastDate(row.archivedAt)&&row.path===row.run.slice(0,10).replace(/-/g,'')+'00.json'&&!archiveNames.has(name)&&m.objects[name]?.sha256===row.sha256,'Archive index reference mismatch');archiveNames.add(name)}forecastAssert(Object.keys(m.objects).filter(n=>/^archive\/[0-9]/.test(n)).every(n=>archiveNames.has(n)),'Unindexed archive object');
    for(const name of changed.filter(n=>archiveNames.has(n))){const item=await bucket.get(forecastObjectKey(m.objects[name].sha256,name)),record=forecastJSON(await item.arrayBuffer()),entry=archiveIndex.issuances.find(r=>'archive/'+r.path===name);forecastAssert(record.schemaVersion===1&&record.run===entry.run&&record.archivedAt===entry.archivedAt&&record.model==='NOAA CFSv2'&&[4,8,12,16].includes(record.memberCount)&&Array.isArray(record.locations)&&record.locations.length>0&&record.locations.length<=10,'Invalid issued forecast archive');for(const location of record.locations)forecastAssert(typeof location.name==='string'&&Array.isArray(location.periods)&&[8,9].includes(location.periods.length)&&location.periods.every(period=>forecastDate(period.intervalStart)&&forecastDate(period.intervalEndExclusive)&&['temperature','precipitationRate'].every(field=>['p10','p50','p90'].every(q=>Number.isFinite(period[field]?.[q])))),'Invalid archive periods')}
    m.publication={runID:writer.run_id,attempt:Number(writer.run_attempt),commit:writer.sha,publishedAt:new Date(clock()).toISOString()};
    const body=JSON.stringify(m),releaseKey='forecasts/releases/'+m.releaseID+'.json';await bucket.put(releaseKey,body,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/json'}});
    const result=await bucket.put(FC_LATEST,body,{onlyIf:current?{etagMatches:current.item.etag}:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/json'}});forecastAssert(result,'Manifest changed during publication',412);return forecastResponse(JSON.stringify({releaseID:m.releaseID,published:true}),200,{'content-type':'application/json',etag:result.httpEtag||'"'+result.etag+'"'});
   }
   return forecastResponse('Not found',404);
  }catch(error){return forecastResponse(JSON.stringify({error:error.status?error.message:'Forecast service temporarily unavailable'}),error.status||503,{'content-type':'application/json'})}
 },async active(request,env,name){try{forecastAssert(FORECAST_FILES.includes(name)||/^archive\/(?:index|[0-9]{8}00)\.json$/.test(name),'Unsupported forecast',404);forecastAssert(env?.FORECASTS,'Forecast storage unavailable',503);const current=await latest(env.FORECASTS);forecastAssert(current,'Forecast bundle not yet available',404);const meta=current.data.objects[name];forecastAssert(meta,'Forecast object unavailable',404);const response=await readObject(env.FORECASTS,meta.sha256,name,request.method==='HEAD');const headers=new Headers(response.headers);headers.set('cache-control','no-store');return new Response(response.body,{status:response.status,headers})}catch(e){return forecastResponse(JSON.stringify({error:e.status?e.message:'Forecast service temporarily unavailable'}),e.status||503,{'content-type':'application/json'})}}};
}
